### ISSUE TITLE
Superset error | Error during planning: Invalid function 'pg_catalog.version'

### ISSUE THREAD

**Issue by atul-r** [sunng87/greptimedb-sqlalchemy#1]
I have started greptimedb in the docker running the following command `docker run -d --security-opt seccomp=unconfined -p 4000-4003:4000-4003 -v "C:\Users\atram\Documents\genai\others\greptimepath:/tmp/greptimedb" --name greptime greptime/greptimedb:v0.9.1 standalone start --http-addr 0.0.0.0:4000 --rpc-addr 0.0.0.0:4001 --mysql-addr 0.0.0.0:4002 --postgres-addr 0.0.0.0:4003`

then created a table in supersetexample database called app_logs and inserted some dummy data using the following query
```
CREATE TABLE app_logs (
	  ts TIMESTAMP TIME INDEX,
	  host STRING,
	  api_path STRING FULLTEXT,
	  log_level STRING,
	  log STRING FULLTEXT,
	  PRIMARY KEY (host, log_level)
	)
	engine=mito with('append_mode'='true');
```

After that, I am trying to access it through sqlalchemy using the `greptimedb-sqlalchemy` library. Shared the code below

```
from sqlalchemy import create_engine, text, inspect

query = "select * from app_logs limit 10;"
conn_string = "greptimedb://root:greptime_pwd@127.0.0.1:4003/supersetexample"

engine = create_engine(conn_string)
try:
    with engine.begin() as connection:
        result = connection.execute(text(query))
        for row in result:
            print(row)
    print("Connection successful!")
except Exception as e:
    print("Connection failed:", e)
```

__I am getting the same error that I get when I try to connect using superset UI__ . The error is below

`Connection failed: Failed to plan SQL: Error during planning: Invalid function 'pg_catalog.version'.
Did you mean 'APPROX_MEDIAN'?`

**Comment by sunng87** [comment]
@atul-r could you help to me verify if this issue persists on greptimedb 0.9.3 ?

**Comment by atul-r** [comment]
> @atul-r could you help to me verify if this issue persists on greptimedb 0.9.3 ?

@sunng87 this error is not present in greptimedb 0.9.3 but there I am getting issue with GreptimeDBEngineSpec.get_indexes() method. See the error message below. This happens when I try to create dataset in superset (basically reading the table details)

```
2024-09-16 13:16:00 2024-09-16 07:46:00,047:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.table_metadata.error
2024-09-16 13:16:00 2024-09-16 07:46:00,047:ERROR:flask_appbuilder.api:GreptimeDBEngineSpec.get_indexes() takes 4 positional arguments but 5 were given
2024-09-16 13:16:00 Traceback (most recent call last):
2024-09-16 13:16:00   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
2024-09-16 13:16:00     return f(self, *args, **kwargs)
2024-09-16 13:16:00   File "/app/superset/views/base_api.py", line 127, in wraps
2024-09-16 13:16:00     raise ex
2024-09-16 13:16:00   File "/app/superset/views/base_api.py", line 121, in wraps
2024-09-16 13:16:00     duration, response = time_function(f, self, *args, **kwargs)
2024-09-16 13:16:00   File "/app/superset/utils/core.py", line 1470, in time_function
2024-09-16 13:16:00     response = func(*args, **kwargs)
2024-09-16 13:16:00   File "/app/superset/utils/log.py", line 255, in wrapper
2024-09-16 13:16:00     value = f(*args, **kwargs)
2024-09-16 13:16:00   File "/app/superset/databases/api.py", line 742, in table_metadata
2024-09-16 13:16:00     table_info = get_table_metadata(database, table_name, schema_name)
2024-09-16 13:16:00   File "/app/superset/databases/utils.py", line 74, in get_table_metadata
2024-09-16 13:16:00     indexes = get_indexes_metadata(database, table_name, schema_name)
2024-09-16 13:16:00   File "/app/superset/databases/utils.py", line 39, in get_indexes_metadata
2024-09-16 13:16:00     indexes = database.get_indexes(table_name, schema_name)
2024-09-16 13:16:00   File "/app/superset/models/core.py", line 855, in get_indexes
2024-09-16 13:16:00     return self.db_engine_spec.get_indexes(self, inspector, table_name, schema)
2024-09-16 13:16:00 TypeError: GreptimeDBEngineSpec.get_indexes() takes 4 positional arguments but 5 were given
2024-09-16 13:16:00 172.20.0.1 - - [16/Sep/2024:07:46:00 +0000] "GET /api/v1/database/11/table/app_logs/supersetexample/ HTTP/1.1" 500 31 "http://localhost:8088/dataset/add/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
```

**Comment by atul-r** [comment]
@sunng87  I tried changing the number of arguments in the method [here](https://github.com/sunng87/greptimedb-sqlalchemy/blob/444f6ccc895e21a11a5789e4476b0ac6195d4ecc/src/greptimedb_sqlalchemy/superset.py#L174)
It is able to read the table now. But in superset when i try to create a chart it doesn't work. The query that superset creates is 
```
SELECT DATE_ADD(DATE(ts), INTERVAL (HOUR(ts)*60*60 + MINUTE(ts)*60 + SECOND(ts)) SECOND) AS ts,
       AVG(latency) AS `AVG(latency)`
FROM supersetexample.grpc_latencies
GROUP BY DATE_ADD(DATE(ts), INTERVAL (HOUR(ts)*60*60 + MINUTE(ts)*60 + SECOND(ts)) SECOND)
ORDER BY `AVG(latency)` DESC
LIMIT 10000;
```

This doesn't work with greptimedb v0.9.3. The error is
```
Failed to plan SQL: Error during planning: Invalid function 'date'.
Did you mean 'MAX'?
```

**Comment by sunng87** [comment]
Hello @atul-r , thank you for reporting!

May I know the version of superset you are using? This plugin is developed against the master branch of superset. Also it seems your SQL is generated as in MySQL dialect. Were you using the visualization builder from superset to generate that SQL? Our plugin defined it should use postgres' `date_trunc` function for that. 

A sample SQL generated by me:

```
superset_app          | 2024-09-16 20:28:25,719:DEBUG:superset.sql_parse:Parsing with sqlparse statement: SELECT
superset_app          |   DATE_TRUNC('MINUTE', ts) AS ts,
superset_app          |   host AS host,
superset_app          |   device AS device,
superset_app          |   MAX(val) AS "MAX(val)"
superset_app          | FROM public.host_network_receive_bytes_total
superset_app          | GROUP BY
superset_app          |   DATE_TRUNC('MINUTE', ts),
superset_app          |   host,
superset_app          |   device
superset_app          | ORDER BY
superset_app          |   "MAX(val)" DESC
superset_app          | LIMIT 10000

```

**Comment by sunng87** [comment]
@atul-r just check in to see if you have any other issue with connecting greptimedb and superset?

**Comment by atul-r** [comment]
I was able to get it working with the latest master of superset. Thanks @sunng87

**Comment by sunng87** [comment]
Thank you! Let me know if you have any further questions.
